name: Concurrency with workflow.
run-name: Triggered by ${{github.actor}} - ${{github.run_id}}.
on:
  workflow_dispatch:
    inputs:
      name:
        description: Pass your name.
        required: true
        type: string
        default: world
#concurrency: concurrency-group

jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      cache-dir: cache-data
      cache-file: prev-val
    steps:
      - name: Restore data from cache.
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: ${{env.cache-dir}}
          key: concurrency-cache
      - name: Print previous value.
        if: steps.restore-cache.outputs.cache-hit == 'true'
        run: |
          echo 'Cache contents:'
          echo $(ls -a ${{env.cache-dir})
          export PREVIOUS_VALUE=$(cat ${{env.cache-dir}}/${{env.cache-file}})
          echo "Previous value was - ${PREVIOUS_VALUE}."
      - name: Processing data ...
        run: sleep 1
      - name: Print name.
        run: echo Hello ${{inputs.name}}!!!
      - name: Update cache.
        run: echo ${{inputs.name}} > ${{env.cache-dir}}/${{env.cache-file}}
