name: Concurrency with workflow.
run-name: Triggered by ${{github.actor}} - ${{github.run_id}}.
on:
  workflow_dispatch:
    inputs:
      name:
        description: Pass your name.
        required: true
        type: string
        default: world
#concurrency: concurrency-group

jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      cache-dir: cache-data
      cache-file: prev-val
      cache-dir1: cache-data1
      cache-file1: prev-val1
      cache-key: concurrency-cachev
    steps:
      - name: Restore data from cache.
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{env.cache-dir}}
          key: ${{env.cache-key}}
      - name: Create directory if not exists.
        #if: steps.restore-cache.outputs.cache-hit != 'true'
        run: mkdir ${{env.cache-dir1}}
      - name: Print previous value.
        if: steps.restore-cache.outputs.cache-hit == 'true'
        run: |
          echo 'Cache contents:'
          echo $(ls -a ${{env.cache-dir}})
          export PREVIOUS_VALUE=$(cat ${{env.cache-dir}}/${{env.cache-file}})
          echo "Previous value was - ${PREVIOUS_VALUE}."
      - name: Processing data ...
        run: sleep 1
      - name: Print name.
        run: echo Hello ${{inputs.name}}!!!
      - name: Update cache.
        run: echo ${{inputs.name}} > ${{env.cache-dir1}}/${{env.cache-file1}}
      - name: Save cache.
        id: save-cache
        uses: actions/cache/save@v3
        with:
          path: ${{env.cache-dir1}}
          key: ${{env.cache-key1}}
