name: Concurrency with workflow.
run-name: Triggered by ${{github.actor}} - ${{github.run_id}}.
on:
  workflow_dispatch:
    inputs:
      name:
        description: Pass your name.
        required: true
        type: string
        default: world

jobs:
  hello:
    runs-on: ubuntu-latest
    concurrency: 
      group: concurrency-group
      #cancel-in-progress: true
    steps:
      - name: Processing data ...
        run: sleep 30
      - name: Print name.
        run: echo Hello ${{inputs.name}}!!!
