name: Demo Workflow
on: [workflow_dispatch]
jobs:
  hello-user:
    runs-on: ubuntu-latest
    steps:
      - name: print-message
        run: echo "Hello ${GITHUB_ACTOR}, now you triggered workflow from ${GITHUB_BASE_REF} branch." 
