name: Demo Workflow
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Pass your name.'
        required: true
        default: 'Test'
        type: string
      surname:
        description: 'Pass your surname.'
        required: true
        default: 'Test'
        type: string
      is_run-multiple-commands:
        description: Run multiple commands or not.
        required: true
        default: false
        type: choice
        options:
          - 'true'
          - 'false'
jobs:
  hello-user:
    runs-on: ubuntu-latest
    steps:
      - name: print-message
        run: echo "Hello ${GITHUB_ACTOR}, now you triggered workflow from the ${GITHUB_REF_NAME} branch."
      - if: ${{inputs.is_run-multiple-commands == 'true'}}
        name: run-multiple-commands
        run: |
          echo "Your name is ${{inputs.name}}"
          echo "Your surname is ${{inputs.surname}}"
